name: Create device for PR

on:
  pull_request:
    branches:
      - master
    # types:
    # - created

jobs:
  create-iot-hub-device:
    name: Create PR IoT Device
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az extension add --name azure-iot

          az iot hub device-identity create \
            --device-id pr-${{ github.event.number }} \
            --am shared_private_key \
            --hub-name azure-iot-sdk-rs \
            --resource-group azure-iot-sdk-rs \
            --login "${{ secrets.IOTHUB_ENTITY_CONNECTION_STRING }}"
